### ISSUE TITLE
Volatility module must be installed manually rather than from pip

### ISSUE THREAD

**Issue by lsassx64** [volatilityfoundation/volumetric#1]
I've been trying to get this working for a while but unsuccessful...

Whatever I do I hit a wall with the last step where voaltility gives me error - no module volatility installed?!?
This is my screen output:

C:\Users\test\Desktop\volumetric-master>py -3 -m pip freeze
cheroot==8.2.1
CherryPy==18.4.0
jaraco.functools==2.0
more-itertools==7.2.0
npm==0.1.1
optional-django==0.1.0
portend==2.6
pytz==2019.3
pywin32==227
six==1.13.0
tempora==1.14.1
volatility3==0.0.2
zc.lockfile==2.0

C:\Users\test\Desktop\volumetric-master>py -3 vol.py
Traceback (most recent call last):
  File "vol.py", line 7, in <module>
    from volumetric import server
  File "C:\Users\test\Desktop\volumetric-master\volumetric\server.py", line 13, in <module>
    import volumetric.api
  File "C:\Users\test\Desktop\volumetric-master\volumetric\api.py", line 16, in <module>
    import volatility
ModuleNotFoundError: No module named 'volatility'

Any help would be apriciated!

**Comment by ikelos** [comment]
Hiya, currently the `pip` package for volatility3 is just a placeholder.  We're working to resolve this, but unfortunately it's dependent on another party.

You either need to install the volatility3 package directly from [github](https://github.com/volatilityfoundation/volatility3), or download a copy and put it in the volumetric source directory.  Once it's there, the error should go away.  Failing that, you can also use the precompiled executable which should contain a copy of volatility3.

Please let us know whether that resolves your problem, and then we can either investigate further or close this ticket off...  5:)

**Comment by lsassx64** [comment]
Hi,
hmmmm im still stupid...can you lay down the exact folder structure for me in side the volumetric-master? 
Precompiled executable which shoud contain a copy of vol3? Completely lost me there sorry :(

**Comment by ikelos** [comment]
Sure, so the directory structure would look like:
```
/vol.py
/resources/
/volatility/
/volatility/framework/
...
/volumetric/
...
```

As to the precompiled executable, you can find on the releases page, under the 1.0 release, you can find the [volumetric-windows-binaries-1.0.0-beta.1.zip](https://github.com/volatilityfoundation/volumetric/releases/download/v1.0.0-beta.1/volumetric-windows-binaries-1.0.0-beta.1.zip) which contains a volumetric.exe that should run standalone (ie, it already contains a copy of volatility3 inside it).  You could always give that a try rather than trying to get the source going directly?

**Comment by lsassx64** [comment]
Ah such a git....
The precompiled one works like a charm of course!

When I do it manually, i get the server running but all I see is a blank page. I still must have my folders messed up somehow

![Annotation 2019-11-18 234553](https://user-images.githubusercontent.com/14116246/69100553-b863b580-0a5d-11ea-931a-f442ecc26767.png)

**Comment by ikelos** [comment]
Hmmm, it doesn't look like you've run `npm install`.  You need to have a copy of node installed (to get `npm`), in order to download all the javascript requirements for the frontend (they're also all included in the executable).

If you do that step you should see a `node_modules` in the top level, and you should also find one under the `resources` directory too (if you don't, it means something went wrong during the `npm install` stage).  Give that a try and hopefully it'll give you actual page display...  5:)

**Comment by ikelos** [comment]
I believe that the pip package now installs correctly (however, the latest version now requires version 2.5.2 which is currently only available in git).  Please don't forget to run `npm install` from the root.  I'm going to close this off, but feel free to reopen this after 2.5.2 has been released (probably in late January 2023), if the installation via pip doesn't work correctly...
